### PR TITLE
security check for bop

### PR DESCRIPTION
**Pull request by hgdubbe**
bop usage on tanks on/off for obvious reasons

### CODE REVIEW

**Comment by adde88** [comment]
You're trying to avoid using BoP on tanks correct?

**Comment by hgdubbe** [comment]
its aswitch if bop should be used on tanks or not as it causes instant aggro loss

**Comment by adde88** [comment]
You want a switch, if enabled it will use it on tanks as well?
If not enabled, it will not?

**Comment by hgdubbe** [comment]
yep

**Pull request closed without merging**
